### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by ivanberry** [FeeiCN/grw#30]
### Chromium 45

点击注册或者立刻登录都会跳转到QQ，但是填写QQ信息后没有进入登入页面，一片空白，觉得这个非常好，从zhihu知道的，我是一枚自学的前端小菜鸡，向大大学习。

**Comment by kltt22** [comment]
同样出现此问题

**Comment by dwhdrbdhs** [comment]
mac OSX Chrome
同样的问题
服务器返回500错误

**Comment by zxszx4** [comment]
win10 firefox 同样问题
Edge显示500错误

**Comment by zg55** [comment]
我也注册不了是怎么回事

**Comment by fitoe** [comment]
+1

**Comment by Aaronleb** [comment]
qq登录的接口有问题，无法注册登录
